global:
  scrape_interval: 5s # Intervalo em que o Prometheus coleta as métricas

scrape_configs:
  - job_name: 'api_autos'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'api_autos'